### ISSUE TITLE
don't use create-react-app use next.js

### ISSUE THREAD

**Issue by rishawdev** [jalbertsr/react-movies-app#37]
# [Next.js](https://nextjs.org)
- Use [SSR (server-side rendering)](https://nextjs.org/learn/seo/rendering-and-ranking/rendering-strategies) to make the site SEO friendly
- Deploy The Site on vercel.
- Since so many images are on the website, you can optimize those images with the [next.js image component](https://nextjs.org/docs/basic-features/image-optimization)

### Go with tailwindCSS to make the CSS part easy
@jalbertsr

**Comment by jalbertsr** [comment]
Very nice recommendations! I Agree on everything! 
That would definitely be my way to go nowadays, but this project was done 5 years ago, and now is unmaintained.

If you would like to do all those changes feel free to open a PR 😀

**Comment by jalbertsr** [comment]
hello, @Rishaw-Developer If you are going to do it feel free to reopen the issue and assign it to yourself.

**Comment by rishawdev** [comment]
Since this project isn't being maintained. I am not going to make this app with next but I shall like to contribute to your latest repositories. 
@jalbertsr 
Thanks
